#!/usr/bin/env node
/*
 * Deterministically generate the skill-IMPROVER loop conductor (a Workflow `.js` script) from a
 * skill slug. A fork of prospector's scaffold-optimize.cjs: same two-layer Workflow shape, but it
 * emits a FIXED-BACKLOG GREEN loop instead of a scalar hill-climb. Per backlog item, a `fixer`
 * worker edits the skill to turn a frozen, human-confirmed, baseline-failing acceptance-check
 * green; the conductor keeps the change iff the FLOOR passes AND the CHECK passes AND the
 * SURFACE-LOCK holds (editable = skill minus `evals/**` + backlog), reverting otherwise.
 *
 * Key difference from scaffold-workflow: the RUN CONFIG (skill, surface, floor, items, budgets,
 * baseline) is NOT baked into the template — it is passed to the loop conductor via Workflow
 * `args.config` at launch, so a `resume` re-passes it unchanged (the conductor cannot read fs).
 * The generator therefore bakes only the LOOP STRUCTURE; everything project-specific is data-in.
 *
 * Conductor constraints (same as conductor): the generated loop is PURE JS — no fs, no git, no
 * Date.now()/Math.random(). Every side-effect (worktree create, running the floor/check, edits,
 * commit/revert, ledger writes) happens inside an `agent()` worker prompt.
 *
 * Usage:
 *   node scaffold-improve.cjs --name <slug> [--out <path>] [--force]
 * Options:
 *   --name <slug>   required; kebab slug; drives state/branch/worktree paths and the resume key.
 *   --out <path>    output file (default: .improve/<name>.js).
 *   --force         overwrite an existing output file.
 *
 * Exposes pure decision helpers (surfaceAllows / verdictOf / shouldStop) on module.exports so the
 * regression net (test-improve.cjs) can unit-test them directly — they are ALSO inlined verbatim
 * into the generated conductor (pure JS, legal in the restricted layer).
 */
const fs = require('fs');
const path = require('path');

// --- pure decision helpers: exported for tests AND inlined into the generated loop (legal in the restricted layer) ---
function globToRe(glob) {
  let re = '^';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === '*') { if (glob[i+1] === '*') { re += '.*'; i++; if (glob[i+1] === '/') i++; } else re += '[^/]*'; }
    else if (c === '?') re += '[^/]';
    else if ('\\^$.|+()[]{}'.indexOf(c) !== -1) re += '\\' + c;
    else re += c;
  }
  return new RegExp(re + '$');
}
function surfaceAllows(files, editable, locked) {
  const eds = String(editable || '').split(/[,\n]/).map(s => s.trim()).filter(Boolean).map(globToRe);
  const lks = (Array.isArray(locked) ? locked : String(locked || '').split(/[,\n]/)).map(s => String(s).trim()).filter(Boolean).map(globToRe);
  if (!eds.length || !files.length) return false;
  return files.every(f => {
    const file = String(f).replace(/^\.\//, '');
    if (lks.some(r => r.test(file))) return false;       // locked → blocked (anti-gaming fence)
    return eds.some(r => r.test(file));
  });
}
function verdictOf(floorPassed, checkPassed, surfaceOk) {
  return (floorPassed && checkPassed && surfaceOk) ? 'kept' : 'reverted';
}
function shouldStop(itemsDone, total, elapsedMin, tokensUsed) {
  total = total || {};
  if (typeof total.items === 'number' && itemsDone >= total.items) return 'items';
  if (typeof total.wallclockMin === 'number' && typeof elapsedMin === 'number' && elapsedMin >= total.wallclockMin) return 'wallclock';
  if (typeof total.tokens === 'number' && typeof tokensUsed === 'number' && tokensUsed >= total.tokens) return 'tokens';
  return null;
}
const HELPERS_SRC = [globToRe, surfaceAllows, verdictOf, shouldStop].map(fn => fn.toString()).join('\n\n');

// --- CLI arg parser (forked from scaffold-optimize.cjs) ---
function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  if (i === -1) return def;
  const v = process.argv[i + 1];
  return v && !v.startsWith('--') ? v : true; // bare flag → true
}

function generate(name) {
  return `// AUTO-GENERATED by scaffold-improve.cjs — do NOT hand-edit. Config is data-in via args.config.
// Restricted conductor: pure JS only — no fs/git/Date.now()/Math.random(); side-effects live in agent() workers.
//
// The run CONFIG (skill, surface, floor, items, budgets, baseline) is passed in via Workflow
// \\\`args.config\\\` at launch — NOT baked here — so a resume re-passes it unchanged (the conductor
// cannot read the filesystem). To change the LOOP STRUCTURE, re-run the generator with --force.
//
// Loop shape (spec §2): Setup → Baseline (floor MUST pass) → fixed-backlog GREEN loop (fix → eval
// floor+check+surface → keep-or-revert with surface-lock → checkpoint) → stop on the FIRST of
// {items, wallclockMin, tokens}. KEPT commits accumulate on improve/<name>; never merged (spec §4).

export const meta = {
  name: '${name}',
  description: 'Skill improver loop: ${name} (feedback backlog → fix → floor+check gate → keep/revert)',
  phases: [ { title: 'Setup' }, { title: 'Baseline' }, { title: 'Items' } ],
}

// ---------------------------------------------------------------------------
// Pure decision helpers — inlined from scaffold-improve.cjs (legal in the restricted layer).
// surfaceAllows(files, editable, locked) — the surface-lock fence (editable minus locked).
// verdictOf(floorPassed, checkPassed, surfaceOk) — binary keep iff all three.
// shouldStop(itemsDone, total, elapsedMin, tokensUsed) — first stop reason or null.
// ---------------------------------------------------------------------------
${HELPERS_SRC}

const CONFIG = (args && args.config) ? args.config : null
if (!CONFIG) throw new Error('Missing args.config — launch with { config: <.improve/config/' + '${name}' + '.json> }')
const NAME = '${name}'
const STATE = \`.improve/state/\${NAME}.json\`
const BRANCH = (args && args.branch) ? args.branch : \`improve/\${NAME}\`
const BASELINE = CONFIG.baseline || ''
const WORKTREE = \`.worktrees/improve-\${NAME}\`
const SKILLPATH = CONFIG.skillPath || ''
const EDITABLE = CONFIG.editable || ''
const LOCKED = CONFIG.locked || []
const FLOOR = (CONFIG.floor && CONFIG.floor.cmd) || ''
const ALL_ITEMS = Array.isArray(CONFIG.items) ? CONFIG.items : []
// human-only items (no acceptanceCheck) never enter the autonomous loop — reported, not attempted.
const ITEMS = ALL_ITEMS.filter(it => it && it.acceptanceCheck)
const BUDGETS = CONFIG.budgets || {}
const RETRIES = (typeof BUDGETS.checkRetries === 'number') ? BUDGETS.checkRetries : 2
const AGENTCAP = (typeof BUDGETS.agentCapSec === 'number') ? BUDGETS.agentCapSec : 600
const TOTAL = BUDGETS.total || { items: ITEMS.length }

// resume: re-passed ledger so the conductor skips already-done items.
const priorItems = (args && Array.isArray(args.items)) ? args.items : []
const ledger = priorItems.slice()
const doneIds = new Set(ledger.map(e => e && e.id))
let itemsDone = ledger.length
const results = {}
if (args && args.baseline && typeof args.baseline === 'object') results.baseline = args.baseline

// Per-worker isolation instruction. \`slot\` makes the notes file UNIQUE so parallel/sequential
// workers never clobber each other (vary by item id, never randomness). Pass { notes: false }
// for mechanical steps (commit/revert/checkpoint) that make no design decision.
function inWorktree(slot, opts) {
  const base = \`Work ONLY inside the git worktree at \${WORKTREE} (run \\\`cd \${WORKTREE}\\\` first; it is on \` +
    \`branch \${BRANCH}). Do NOT edit any file outside \${WORKTREE}. Commit your changes there.\`
  if (opts && opts.notes === false) return base
  return base + \`\\n\\nIf — and ONLY if — this step involved a non-trivial design decision, an \` +
    \`intentional deviation from the spec, a tradeoff between real alternatives, or an open question a \` +
    \`reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/\${slot}.html \` +
    \`in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or \` +
    \`no-decision work, SKIP the file — do not create empty or boilerplate notes.\`
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first, then write the
// full canonical ledger. The conductor serializes the bytes; the worker only adds timestamps.
// Mirrors conductor's checkpoint() exactly, but persists the improver ledger schema (items, not
// experiments; baseline.floorPassed, not best/metric).
async function checkpoint(tag, status) {
  const payload = JSON.stringify(
    {
      name: NAME, status: status || 'running',
      branch: BRANCH, worktree: WORKTREE,
      skill: NAME, skillPath: SKILLPATH,
      baseline: results.baseline || null,
      items: ledger,
    },
    null, 2,
  )
  await agent(
    \`Persist the durable improver ledger to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .improve/state
cat > .improve/state/.\${NAME}.payload.json <<'DURABLE_JSON'
\${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='\${STATE}';const p='.improve/state/.\${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;s.finishedAt=prev.finishedAt||null;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('\${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.\`,
    { label: \`checkpoint:\${tag}\`, phase: 'Items',
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
// Branch is improve/<name> in .worktrees/improve-<name>; main is never touched (spec §4).
phase('Setup')
results.setup = await agent(
  \`Create an isolated git worktree for the improver loop. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="\$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/\${WORKTREE}\$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/\${BRANCH}"; then
  git worktree add "\${WORKTREE}" "\${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="\${BASELINE}"
  # Auto-detect the remote's default branch when no baseline was given.
  [ -n "\$BASEREF" ] || BASEREF="\$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "\$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/\$BASEREF"; then
    START="origin/\$BASEREF"
  elif [ -n "\$BASEREF" ] && git show-ref --verify --quiet "\$BASEREF"; then
    echo "NOTE: \$BASEREF is not an origin/ ref — using it verbatim (e.g. a tag/sha/origin-prefixed ref)"; START="\$BASEREF"
  elif [ -n "\$BASEREF" ]; then
    echo "WARN: \$BASEREF not found — branching from current HEAD (may be stale)"; START="HEAD"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching \${BRANCH} from \$START"
  git worktree add "\${WORKTREE}" -b "\${BRANCH}" "\$START"
fi
[ -e "\${WORKTREE}/node_modules" ] || [ ! -d "\$ROOT/node_modules" ] || ln -s "\$ROOT/node_modules" "\${WORKTREE}/node_modules"
test -d "\${WORKTREE}" && echo OK\`,
  { label: 'setup:worktree', phase: 'Setup',
    schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
)

// --- Baseline: the floor MUST pass on the unmodified skill (can't improve a broken skill) ---
phase('Baseline')
if (!(results.baseline && results.baseline.floorPassed)) {
  const base = await agent(
    \`\${inWorktree('baseline', { notes: false })}

BASELINE: run the FLOOR for skill "\${NAME}" on the unmodified worktree — it MUST exit 0:
    \${FLOOR || '(no floor configured — FAIL)'}
Report floorPassed (did it exit 0?) and floorOut (last ~20 lines). Do NOT edit anything.\`,
    { label: 'baseline', phase: 'Baseline',
      schema: { type: 'object', additionalProperties: false, required: ['floorPassed'],
        properties: { floorPassed: { type: 'boolean' }, floorOut: { type: 'string' } } } })
  if (!base || !base.floorPassed) throw new Error('Baseline floor failed — cannot improve a skill whose floor is red: ' + ((base && base.floorOut) || ''))
  results.baseline = { floorPassed: true }
  await checkpoint('baseline')
}

// --- Items: per frozen, discrimination-passed item, GREEN against its check ---
phase('Items')
for (let i = 0; i < ITEMS.length; i++) {
  const item = ITEMS[i]
  if (doneIds.has(item.id)) continue                     // resume: skip completed items
  const stop = shouldStop(itemsDone, TOTAL, (args && args.elapsedMin), (args && args.tokensUsed))
  if (stop) { log(\`Stopping: \${stop} budget reached (itemsDone=\${itemsDone})\`); break }

  // (a) FIX (GREEN) — bounded; edit ONLY the editable surface to turn the FROZEN check green. Retry ≤ RETRIES.
  const fix = await agent(
    \`\${inWorktree(\`fix-\${item.id}\`)}

FIX item "\${item.id}" (\${item.type}): \${item.text}
Edit ONLY files in the editable surface \${EDITABLE} (NEVER touch \${JSON.stringify(LOCKED)} — that is locked).
Make the item's FROZEN acceptance-check pass:
    \${item.acceptanceCheck}
You have a soft budget of \${AGENTCAP}s and up to \${RETRIES + 1} attempts; re-run the check yourself and iterate.
Do NOT edit the check, any evals/ file, or the backlog. Do NOT commit — the eval step decides keep/revert.
Describe your fix in one line as \\\`change\\\`.\`,
    { label: \`fix:\${item.id}\`, phase: 'Items',
      schema: { type: 'object', additionalProperties: false, required: ['change'],
        properties: { change: { type: 'string' }, summary: { type: 'string' } } } })
  const change = (fix && fix.change) || '(no change)'

  // (b) EVAL — floor + the item's check + surface diff (worker measures only; conductor decides).
  const evalRes = await agent(
    \`\${inWorktree(\`eval-\${item.id}\`, { notes: false })}

EVAL item "\${item.id}" — measure, do NOT commit/revert:
1. FLOOR (must still pass): \${FLOOR}  → report floorPassed (exit 0?).
2. ACCEPTANCE CHECK: \${item.acceptanceCheck}  → report checkPassed (exit 0?).
3. SURFACE: report diffFiles = EVERY changed path incl. untracked, via:
       git -c core.quotepath=false status --porcelain --untracked-files=all
   (the path after the 2-char status; for \\\`R old -> new\\\` the NEW path).\`,
    { label: \`eval:\${item.id}\`, phase: 'Items',
      schema: { type: 'object', additionalProperties: false, required: ['floorPassed','checkPassed','diffFiles'],
        properties: { floorPassed: { type: 'boolean' }, checkPassed: { type: 'boolean' },
          diffFiles: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } } } })

  const floorPassed = !!(evalRes && evalRes.floorPassed)
  const checkPassed = !!(evalRes && evalRes.checkPassed)
  const diffFiles = (evalRes && Array.isArray(evalRes.diffFiles)) ? evalRes.diffFiles : []
  const surfaceOk = surfaceAllows(diffFiles, EDITABLE, LOCKED)
  const verdict = verdictOf(floorPassed, checkPassed, surfaceOk)

  let sha = null
  if (verdict === 'kept') {
    const c = await agent(
      \`\${inWorktree(\`keep-\${item.id}\`, { notes: false })}
KEEP item "\${item.id}": floor + check passed and surface-lock confirmed every change ⊆ the surface.
    git add -A && git commit -m "whetstone(\${NAME}) \${item.id}: \${change}"
Report the commit \\\`sha\\\`. Do not push or merge.\`,
      { label: \`keep:\${item.id}\`, phase: 'Items',
        schema: { type: 'object', additionalProperties: false, required: ['sha'], properties: { sha: { type: 'string' } } } })
    sha = (c && c.sha) || null
  } else {
    await agent(
      \`\${inWorktree(\`revert-\${item.id}\`, { notes: false })}
REVERT item "\${item.id}" (\${!floorPassed ? 'floor broke' : !surfaceOk ? 'touched a locked/out-of-surface file' : 'check did not pass'}).
Reset the WHOLE worktree so it is clean for the next item (prior KEPT commits stay on \${BRANCH}):
    git reset --hard HEAD && git clean -fd
Confirm \\\`git status --porcelain\\\` is empty; report clean.\`,
      { label: \`revert:\${item.id}\`, phase: 'Items',
        schema: { type: 'object', additionalProperties: false, required: ['clean'], properties: { clean: { type: 'boolean' } } } })
  }

  const finalVerdict = (verdict === 'kept') ? 'kept' : (floorPassed && surfaceOk && !checkPassed ? 'unresolved' : 'reverted')
  ledger.push({ id: item.id, type: item.type, change, floor: floorPassed ? 'pass' : 'fail', check: checkPassed ? 'pass' : 'fail', verdict: finalVerdict, sha })
  itemsDone = ledger.length
  await checkpoint(\`item-\${item.id}\`)
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE,
  skill: NAME, humanOnly: ALL_ITEMS.filter(it => !it.acceptanceCheck).map(it => it.id),
  itemsDone, items: ledger }
`;
}

module.exports = { surfaceAllows, verdictOf, shouldStop, generate };

// --- CLI entry (skip when require()'d by the test net; forked from scaffold-optimize.cjs) ---
if (require.main === module) {
  const name = arg('name');
  if (!name || name === true) { console.error('ERROR: --name <slug> is required'); process.exit(1); }
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) { console.error('ERROR: --name must be a kebab slug (a-z0-9-)'); process.exit(1); }
  const out = arg('out', path.join('.improve', name + '.js'));
  const force = arg('force', false) === true;
  if (fs.existsSync(out) && !force) { console.error(`ERROR: ${out} exists (use --force to overwrite)`); process.exit(1); }

  const src = generate(name);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, src);
  console.log(`Generated ${out}`);
  console.log('Phases: Setup → Baseline → Items');
  console.log('Launch via the Workflow tool with args.config = the approved .improve/config/' + name + '.json (config is data-in, NOT baked).');
}
