// AUTO-GENERATED by scaffold-workflow.cjs — do NOT hand-edit.
// Work-phase prompts come from --prompt/--prompts-file (data-in). To change a prompt OR the
// structure, re-run the generator with --force. A leftover \`TODO:\` means a prompt wasn't
// supplied — fill it by regenerating, not by editing this file.
//
// Conductor rules: pure JS only — no fs/git, no Date.now()/Math.random().
// All side-effects happen inside agent() subagents.
//
// Resume semantics: phases are AT-LEAST-ONCE on resume. We checkpoint AFTER the
// side-effect, so a crash between side-effect and checkpoint re-runs that phase.
// Every phase MUST therefore be idempotent. phasesDone is trusted only after the
// entry guard below validates it is a contiguous prefix of the phase order.

export const meta = {
  name: 'snap',
  description: 'Durable workflow: snap',
  phases: [
    { title: 'Setup' },
    { title: 'RED' },
    { title: 'Implement' },
    { title: 'Verify' },
    { title: 'PathGap' },
    { title: 'CodeGate' },
    { title: 'ReVerify' },
  ],
}

// Some Workflow harnesses deliver `args` as a JSON STRING rather than an object; normalize
// once here (BEFORE any args read) so every `(args && args.X)` guard below works either way.
// Uses only typeof + JSON.parse — both allowed at the restricted conductor layer.
if (typeof args === 'string') args = JSON.parse(args)

const NAME     = 'snap'
const STATE    = `.workflows/state/${NAME}.json`
const BRANCH   = (args && args.branch) ? args.branch : `wf/${NAME}`
const BASE     = (args && args.base) ? args.base : ''
const WORKTREE = `.worktrees/${NAME}`
const TICKET   = (args && args.ticket) ? args.ticket : null

const prior = (args && args.results) ? args.results : {}
const done  = new Set((args && args.phasesDone) ? args.phasesDone : [])
const results = { ...prior }

// --- Resume reachability guard: phasesDone MUST be a contiguous prefix ---
// Canonical order is baked in as a literal — the Workflow runtime consumes `meta` as
// metadata, so it is NOT a runtime binding in this body. A durable state that marks a
// phase done while an earlier phase is not is unreachable (corrupt/forged) — reject it
// loudly instead of silently skipping required setup work.
;(() => {
  const order = ["Setup","RED","Implement","Verify","PathGap","CodeGate","ReVerify"]
  for (const title of done) {
    if (!order.includes(title)) {
      throw new Error(`Unreachable resume: phasesDone has unknown phase '${title}' (not in order: ${order.join(' → ')})`)
    }
  }
  // Walk the order; once we hit the first NOT-done phase, no later phase may be done.
  let seenGap = false
  for (const title of order) {
    if (done.has(title)) {
      if (seenGap) {
        throw new Error(`Unreachable resume: phase '${title}' is done but an earlier required phase is not — phasesDone must be a contiguous prefix of [${order.join(' → ')}], got [${[...done].join(', ')}]`)
      }
    } else {
      seenGap = true
    }
  }
})()

// Per-worker instruction. `slot` makes the notes file UNIQUE so parallel / multiple agents
// never clobber each other. For a parallel fan-out, pass a slot unique per item (e.g. `phase-${i}`).
// Pass { notes: false } for mechanical steps (PR push, etc.) that make no design decisions —
// they should NOT create a notes file at all. Where notes ARE offered they are judgment-gated:
// write one ONLY if there is something a reviewer genuinely needs.
function inWorktree(slot, opts) {
  const base = `Work ONLY inside the git worktree at ${WORKTREE} (run \`cd ${WORKTREE}\` first; it is on ` +
    `branch ${BRANCH}). Do NOT edit any file outside ${WORKTREE}. Commit your changes there.`
  if (opts && opts.notes === false) return base
  return base + `\n\nIf — and ONLY if — this step involved a non-trivial design decision, an ` +
    `intentional deviation from the spec, a tradeoff between real alternatives, or an open question a ` +
    `reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/${slot}.html ` +
    `in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or ` +
    `no-decision work, SKIP the file — do not create empty or boilerplate notes.`
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first.
async function checkpoint(phaseTitle) {
  const payload = JSON.stringify(
    { workflow: NAME, status: 'running', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results },
    null, 2,
  )
  await agent(
    `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
    { label: `checkpoint:${phaseTitle}`, phase: phaseTitle,
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
phase('Setup')
if (done.has('Setup')) {
  log('Setup already complete (resumed)')
} else {
  results.setup = await agent(
    `Create an isolated git worktree. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/${WORKTREE}$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "${WORKTREE}" "${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="${BASE}"
  # Auto-detect the remote's default branch when no --base was given.
  [ -n "$BASEREF" ] || BASEREF="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/$BASEREF"; then
    START="origin/$BASEREF"
  elif [ -n "$BASEREF" ]; then
    echo "WARN: origin/$BASEREF not found — branching from local $BASEREF (may be stale)"; START="$BASEREF"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching ${BRANCH} from $START"
  git worktree add "${WORKTREE}" -b "${BRANCH}" "$START"
fi
[ -e "${WORKTREE}/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "${WORKTREE}/node_modules"
test -d "${WORKTREE}" && echo OK`,
    { label: 'setup:worktree', phase: 'Setup',
      schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
  )
  done.add('Setup')
  await checkpoint('Setup')
}

phase('RED')
if (done.has('RED')) {
  log('RED already complete (resumed)')
} else {
  results.red = await agent(
    `${inWorktree('red')}

RED (test-first): from the goal${TICKET ? ' / ticket ' + TICKET : ''} and its acceptance criteria, write the tests BEFORE any implementation. Decide per behavior whether it needs a tryve E2E (tests/e2e/*.yaml) or a Jest unit test, and write them. Run them and CONFIRM THEY FAIL for the right reason — a test that already passes is not exercising the new behavior; fix it until it fails. Commit the failing tests.`,
    { label: 'red', phase: 'RED', agentType: 'lirbox:lirbox-test-writer',
      schema: { type: 'object', additionalProperties: false, required: ["red"], properties: {"red":{"type":"boolean"},"tests":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.red || !results.red.red) throw new Error('RED failed: tests did not establish a failing baseline — ' + (results.red && results.red.summary || ''))
  done.add('RED')
  await checkpoint('RED')
}

phase('Implement')
if (done.has('Implement')) {
  log('Implement already complete (resumed)')
} else {
  results.implement = await agent(
    `${inWorktree('Implement')}

GREEN: implement until the RED tests pass; never weaken or delete tests to go green.

Implement the change described in the run brief.`,
    { label: 'implement', phase: 'Implement', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Implement')
  await checkpoint('Implement')
}

phase('Verify')
if (done.has('Verify')) {
  log('Verify already complete (resumed)')
} else {
  results.verify = await agent(
    `${inWorktree('verify')}

VERIFY (GREEN): run the full relevant test suite for the changes on ${BRANCH} vs ${BASE || 'the base branch'} (Jest unit + any tryve E2E from RED). EVERYTHING must pass. If any test fails, the implementation is incomplete — STOP and report which failed; do NOT weaken tests to pass.`,
    { label: 'verify', phase: 'Verify', schema: { type: 'object', additionalProperties: false, required: ["green"], properties: {"green":{"type":"boolean"},"failing":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.verify || !results.verify.green) throw new Error('Verify failed: not green — ' + (results.verify && (results.verify.failing || []).join(', ')))
  done.add('Verify')
  await checkpoint('Verify')
}

phase('PathGap')
if (done.has('PathGap')) {
  log('PathGap already complete (resumed)')
} else {
  // Close test gaps for code paths the ACs never specified (decide-or-justify, hard-fail).
  let passed = false, last = null
  for (let round = 1; round <= 3 && !passed; round++) {
    const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
    last = await agent(
      `${inWorktree('pathgap')}

PATH-GAP: the ACs do NOT cover every code path. Steps:
1. Run Jest with BRANCH coverage; intersect with the CHANGED lines (git diff vs ${BASE || 'the base branch'}) to find uncovered branches introduced by this change.
2. For EACH uncovered changed branch, do ONE: (a) add a unit/integration test that meaningfully exercises AND asserts it, or (b) if it is genuinely unreachable/defensive, record an explicit justification in implementation-notes/pathgap.html.
3. Re-run coverage. There must be NO silent gaps — every uncovered changed branch is either tested or justified.
Do NOT delete/alter source branches just to raise coverage. Commit new tests + notes.` + carry,
      { label: `pathgap:r${round}`, phase: 'PathGap',
        schema: { type: 'object', additionalProperties: false, required: ["closed"], properties: {"closed":{"type":"boolean"},"uncovered":{"type":"number"},"tested":{"type":"number"},"justified":{"type":"number"},"summary":{"type":"string"}} } },
    )
    passed = last && last.closed
  }
  if (!passed) throw new Error('PathGap failed: uncovered changed-code branches remain after 3 rounds — ' + (last && last.summary || ''))
  results.pathGap = last
  done.add('PathGap')
  await checkpoint('PathGap')
}

phase('CodeGate')
if (done.has('CodeGate')) {
  log('CodeGate already complete (resumed)')
} else {
  let passed = false, last = null
  for (let round = 1; round <= 3 && !passed; round++) {
    const dod = results.brief ? `\n\nScope this gate to the task's actual goal — judge findings against what the task set out to achieve; do NOT drift into changes unrelated to it.\nGOAL: ${results.brief.goal || '(none)'}` + ((results.brief.acceptanceCriteria || []).length ? `\nACCEPTANCE CRITERIA:\n- ${results.brief.acceptanceCriteria.join('\n- ')}` : '') : ''
    const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
    last = await agent(
      `${inWorktree('codegate')}

Review AND fix the changes on branch ${BRANCH} relative to ${BASE || 'the base branch'} (run git diff in ${WORKTREE}). Run the project build/lint — it MUST pass. Resolve EVERY Critical and High finding (bugs, security, rule violations, quality). Re-run the build after fixes and commit them.
OUTPUT CONTRACT: return gatePassed=true ONLY if every Critical and High finding is fixed or skipped-with-explicit-reason AND the build/lint passes; report critical and high as the counts of findings of each severity left UNRESOLVED after your fixes (both 0 when gatePassed=true).
EVIDENCE: report the exact build/lint command you ran as buildCmd and its numeric exit code as buildExit; if the project has no build/lint, run the closest verification command (e.g. the test suite) and report that instead. The gate rejects gatePassed=true unless buildExit is 0.` + dod + carry,
      { label: `codegate:r${round}`, phase: 'CodeGate', agentType: 'lirbox:lirbox-code-reviewer',
        schema: { type: 'object', additionalProperties: false, required: ["gatePassed","critical","high","buildCmd","buildExit"], properties: {"gatePassed":{"type":"boolean"},"critical":{"type":"number"},"high":{"type":"number"},"summary":{"type":"string"},"buildCmd":{"type":"string"},"buildExit":{"type":"number"}} } },
    )
    passed = last && last.gatePassed && last.buildExit === 0
  }
  if (!passed) throw new Error('CodeGate failed: unresolved Critical/High after 3 rounds — ' + (last && last.summary || ''))
  results.codeGate = last
  done.add('CodeGate')
  await checkpoint('CodeGate')
}

phase('ReVerify')
if (done.has('ReVerify')) {
  log('ReVerify already complete (resumed)')
} else {
  results.reVerify = await agent(
    `${inWorktree('reverify')}

RE-VERIFY: after IMPROVE/SIMPLIFY (CodeGate), re-run the FULL test suite + branch coverage for the changes on ${BRANCH} vs ${BASE || 'the base branch'}. Everything green before must STILL be green and coverage must not have regressed. If a refactor broke anything, STOP and report; do NOT weaken tests.`,
    { label: 'reverify', phase: 'ReVerify', schema: { type: 'object', additionalProperties: false, required: ["green"], properties: {"green":{"type":"boolean"},"regressions":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.reVerify || !results.reVerify.green) throw new Error('ReVerify failed: regression after improve/simplify — ' + (results.reVerify && (results.reVerify.regressions || []).join(', ')))
  done.add('ReVerify')
  await checkpoint('ReVerify')
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results }
