// AUTO-GENERATED by scaffold-workflow.cjs — do NOT hand-edit.
// Work-phase prompts come from --prompt/--prompts-file (data-in). To change a prompt OR the
// structure, re-run the generator with --force. A leftover \`TODO:\` means a prompt wasn't
// supplied — fill it by regenerating, not by editing this file.
//
// Conductor rules: pure JS only — no fs/git, no Date.now()/Math.random().
// All side-effects happen inside agent() subagents.
//
// Resume semantics: phases are AT-LEAST-ONCE on resume. We checkpoint AFTER the
// side-effect, so a crash between side-effect and checkpoint re-runs that phase.
// Every phase MUST therefore be idempotent. phasesDone is trusted only after the
// entry guard below validates it is a contiguous prefix of the phase order.

export const meta = {
  name: 'snap',
  description: 'Durable workflow: snap',
  phases: [
    { title: 'Setup' },
    { title: 'DoDBaseline' },
    { title: 'Brief' },
    { title: 'RED' },
    { title: 'Implement' },
    { title: 'Verify' },
    { title: 'PathGap' },
    { title: 'CodeGate' },
    { title: 'ReVerify' },
    { title: 'DocsGate' },
    { title: 'DoDGate' },
    { title: 'Writeup' },
    { title: 'PR' },
    { title: 'TicketUpdate' },
  ],
}

// Some Workflow harnesses deliver `args` as a JSON STRING rather than an object; normalize
// once here (BEFORE any args read) so every `(args && args.X)` guard below works either way.
// Uses only typeof + JSON.parse — both allowed at the restricted conductor layer.
if (typeof args === 'string') args = JSON.parse(args)

const NAME     = 'snap'
const STATE    = `.workflows/state/${NAME}.json`
const BRANCH   = (args && args.branch) ? args.branch : `wf/${NAME}`
const BASE     = (args && args.base) ? args.base : ''
const WORKTREE = `.worktrees/${NAME}`
const TICKET   = (args && args.ticket) ? args.ticket : null
const DOD_CRITERIA = [{"id":"ac1","text":"unit tests green","tier":"checkable","check":"yarn test"},{"id":"ac2","text":"error message is clear","tier":"judged"}]
// Outer plan-execute-verify attempt cap for the DoD gate (replan loop bound).
const DOD_MAX_ATTEMPTS = 2

const prior = (args && args.results) ? args.results : {}
const done  = new Set((args && args.phasesDone) ? args.phasesDone : [])
const results = { ...prior }

// --- Resume reachability guard: phasesDone MUST be a contiguous prefix ---
// Canonical order is baked in as a literal — the Workflow runtime consumes `meta` as
// metadata, so it is NOT a runtime binding in this body. A durable state that marks a
// phase done while an earlier phase is not is unreachable (corrupt/forged) — reject it
// loudly instead of silently skipping required setup work.
;(() => {
  const order = ["Setup","DoDBaseline","Brief","RED","Implement","Verify","PathGap","CodeGate","ReVerify","DocsGate","DoDGate","Writeup","PR","TicketUpdate"]
  for (const title of done) {
    if (!order.includes(title)) {
      throw new Error(`Unreachable resume: phasesDone has unknown phase '${title}' (not in order: ${order.join(' → ')})`)
    }
  }
  // Walk the order; once we hit the first NOT-done phase, no later phase may be done.
  let seenGap = false
  for (const title of order) {
    if (done.has(title)) {
      if (seenGap) {
        throw new Error(`Unreachable resume: phase '${title}' is done but an earlier required phase is not — phasesDone must be a contiguous prefix of [${order.join(' → ')}], got [${[...done].join(', ')}]`)
      }
    } else {
      seenGap = true
    }
  }
})()

// Per-worker instruction. `slot` makes the notes file UNIQUE so parallel / multiple agents
// never clobber each other. For a parallel fan-out, pass a slot unique per item (e.g. `phase-${i}`).
// Pass { notes: false } for mechanical steps (PR push, etc.) that make no design decisions —
// they should NOT create a notes file at all. Where notes ARE offered they are judgment-gated:
// write one ONLY if there is something a reviewer genuinely needs.
function inWorktree(slot, opts) {
  const base = `Work ONLY inside the git worktree at ${WORKTREE} (run \`cd ${WORKTREE}\` first; it is on ` +
    `branch ${BRANCH}). Do NOT edit any file outside ${WORKTREE}. Commit your changes there.`
  if (opts && opts.notes === false) return base
  return base + `\n\nIf — and ONLY if — this step involved a non-trivial design decision, an ` +
    `intentional deviation from the spec, a tradeoff between real alternatives, or an open question a ` +
    `reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/${slot}.html ` +
    `in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or ` +
    `no-decision work, SKIP the file — do not create empty or boilerplate notes.`
}

// Per-item variant for the planner fan-out: each worker in a dependency level OWNS one
// worktree/branch (branched off the level's integrated base), so siblings never share a working
// tree or index — items dispatched in the SAME parallel() batch may touch the SAME file without
// colliding on it or on .git/index.lock. Same judgment-gated notes contract as inWorktree; notes
// land in the ITEM worktree and ride its branch through the level's integrate merge.
function inItemWorktree(slot, wt, br) {
  return `Work ONLY inside YOUR OWN git worktree at ${wt} (run \`cd ${wt}\` first; it is on ` +
    `branch ${br}, branched off ${BRANCH}). Do NOT edit any file outside ${wt} — sibling workers ` +
    `own the other worktrees. Commit your changes there.\n\nIf — and ONLY if — this step involved ` +
    `a non-trivial design decision, an intentional deviation from the spec, a tradeoff between ` +
    `real alternatives, or an open question a reviewer must confirm, append it to a notes file ` +
    `UNIQUE to you at implementation-notes/${slot}.html in the worktree (mkdir -p the dir; create ` +
    `if missing; APPEND — never clobber). For mechanical or no-decision work, SKIP the file — do ` +
    `not create empty or boilerplate notes.`
}

// --- Runtime plan fan-out: pure JS over a value a PLANNER worker returned ---------------------
// The phase's unit of concurrency is no longer the phase: a planner that has READ the repo returns
// the work items, and these two helpers turn that runtime value into dispatchable batches. Both are
// pure (no fs/git/Date/Math.random) — every side-effect still lives in a worker prompt.

// Normalize the planner's answer into a stable item list: a unique id, a filesystem-safe slug (the
// item's own worktree/branch suffix), and a dependsOn list filtered to ids that actually exist. A
// planner that returns nothing usable degenerates to ONE item carrying the phase's own goal — i.e.
// exactly the single serial worker this phase used to be.
function planItems(res, prefix, fallback) {
  const raw = (res && Array.isArray(res.items)) ? res.items : []
  const items = []
  const ids = new Set()
  const slugs = new Set()
  for (const r of raw) {
    const prompt = (r && typeof r.prompt === 'string') ? r.prompt.trim() : ''
    if (!prompt) continue
    const id = String((r && r.id) || '').trim() || ('item' + (items.length + 1))
    if (ids.has(id)) continue
    let slug = (prefix + '-' + id).replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^[-.]+|[-.]+$/g, '').slice(0, 48)
    if (!slug) slug = prefix + '-item' + (items.length + 1)
    while (slugs.has(slug)) slug = slug + '-' + (items.length + 1)
    ids.add(id)
    slugs.add(slug)
    items.push({
      id,
      slug,
      title: String((r && r.title) || id),
      prompt,
      dependsOn: (r && Array.isArray(r.dependsOn)) ? r.dependsOn.map(String) : [],
    })
  }
  if (!items.length) return [{ id: 'all', slug: prefix + '-all', title: prefix, prompt: fallback, dependsOn: [] }]
  for (const it of items) it.dependsOn = it.dependsOn.filter((d) => d !== it.id && ids.has(d))
  return items
}

// Dependency LEVELS: every item whose dependsOn is already satisfied lands in the same level (one
// parallel() batch); an item waits until every id it depends on has resolved. A dependency cycle
// can never stall the run — the remaining items are emitted as one final level, loudly.
function planLevels(items) {
  let pending = items.slice()
  const settled = new Set()
  const levels = []
  while (pending.length) {
    let level = pending.filter((it) => it.dependsOn.every((d) => settled.has(d)))
    if (!level.length) {
      log('plan: dependency cycle among [' + pending.map((it) => it.id).join(', ') + '] — dispatching them as ONE level')
      level = pending
    }
    const inLevel = new Set(level)
    for (const it of level) settled.add(it.id)
    pending = pending.filter((it) => !inLevel.has(it))
    levels.push(level)
  }
  return levels
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first.
async function checkpoint(phaseTitle) {
  const payload = JSON.stringify(
    { workflow: NAME, status: 'running', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, dod: { criteria: DOD_CRITERIA }, phasesDone: [...done], results },
    null, 2,
  )
  await agent(
    `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
    { label: `checkpoint:${phaseTitle}`, phase: phaseTitle, model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
phase('Setup')
if (done.has('Setup')) {
  log('Setup already complete (resumed)')
} else {
  results.setup = await agent(
    `Create an isolated git worktree. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/${WORKTREE}$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "${WORKTREE}" "${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="${BASE}"
  # Auto-detect the remote's default branch when no --base was given.
  [ -n "$BASEREF" ] || BASEREF="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/$BASEREF"; then
    START="origin/$BASEREF"
  elif [ -n "$BASEREF" ]; then
    echo "WARN: origin/$BASEREF not found — branching from local $BASEREF (may be stale)"; START="$BASEREF"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching ${BRANCH} from $START"
  git worktree add "${WORKTREE}" -b "${BRANCH}" "$START"
fi
[ -e "${WORKTREE}/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "${WORKTREE}/node_modules"
test -d "${WORKTREE}" && echo OK`,
    { label: 'setup:worktree', phase: 'Setup', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
  )
  done.add('Setup')
  await checkpoint('Setup')
}

phase('DoDBaseline')
if (done.has('DoDBaseline')) {
  log('DoDBaseline already complete (resumed)')
} else {
  results.dodBaseline = await agent(
    `${inWorktree('dod-baseline', { notes: false })}

DoD BASELINE (pre-work measurement): for EACH criterion below, run its "check" command inside ${WORKTREE} and record met (exit 0) / unmet (non-zero) / error (could not run). Do NOT fix anything — measure only.

CHECKABLE CRITERIA (JSON): ${JSON.stringify(DOD_CRITERIA.filter((c) => c.tier === 'checkable'))}`,
    { label: 'dod-baseline', phase: 'DoDBaseline', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["baselines"], properties: {"baselines":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["id","status"],"properties":{"id":{"type":"string"},"status":{"type":"string","enum":["met","unmet","error"]}}}}} } },
  )
  done.add('DoDBaseline')
  await checkpoint('DoDBaseline')
}

phase('Brief')
if (!TICKET) {
  log('No ticket — goal came from the invocation text')
} else if (done.has('Brief')) {
  log('Brief already complete (resumed)')
} else {
  results.brief = await agent(
    `Fetch tracker ticket ${TICKET} and write a concise goal + acceptance criteria.
Use ToolSearch to load the tracker tools, then fetch verbatim (do NOT rephrase AC/DoD):
- Jira:   mcp__atlassian__getJiraIssue (issueIdOrKey: "${TICKET}")
- Linear: the Linear MCP get-issue tool, ONLY if a Linear server is connected.`,
    { label: 'brief', phase: 'Brief', model: 'opus', effort: 'high',
      schema: { type: 'object', additionalProperties: false, required: ["goal"], properties: {"title":{"type":"string"},"goal":{"type":"string"},"acceptanceCriteria":{"type":"array","items":{"type":"string"}}} } },
  )
  done.add('Brief')
  await checkpoint('Brief')
}

phase('RED')
if (done.has('RED')) {
  log('RED already complete (resumed)')
} else {
  results.red = await agent(
    `${inWorktree('red')}

RED (test-first): from the goal${TICKET ? ' / ticket ' + TICKET : ''} and its acceptance criteria, write the tests BEFORE any implementation. Decide per behavior whether it needs a tryve E2E (tests/e2e/*.yaml) or a Jest unit test, and write them. Run them and CONFIRM THEY FAIL for the right reason — a test that already passes is not exercising the new behavior; fix it until it fails. Commit the failing tests.`,
    { label: 'red', phase: 'RED', agentType: 'lirbox:lirbox-test-writer', model: 'opus', effort: 'high',
      schema: { type: 'object', additionalProperties: false, required: ["red"], properties: {"red":{"type":"boolean"},"tests":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.red || !results.red.red) throw new Error('RED failed: tests did not establish a failing baseline — ' + (results.red && results.red.summary || ''))
  done.add('RED')
  await checkpoint('RED')
}

phase('Implement')
if (done.has('Implement')) {
  log('Implement already complete (resumed)')
} else {
  // In-phase concurrency: a PLANNER worker (it has READ the repo) returns this phase's items and
  // their dependency edges, then the conductor fans them out BY DEPENDENCY LEVEL — every item whose
  // dependsOn is satisfied ships in ONE parallel() batch, each worker in its OWN worktree/branch,
  // each level integrated back into the run branch before the next level branches off it. The plan
  // is persisted before any item runs, so a resume reuses it instead of re-decomposing. Regenerate
  // with --no-plan-fanout for the single serial worker.
  const goal = `
GREEN: implement until the RED tests pass; never weaken or delete tests to go green.

Implement the change described in the run brief.`
  let items = (results.implementPlan && Array.isArray(results.implementPlan.items) && results.implementPlan.items.length)
    ? results.implementPlan.items
    : null
  if (items) {
    log('Implement: reusing the persisted plan (' + items.length + ' item(s)) — a resume never re-decomposes')
  } else {
    const planned = await agent(
      `${inWorktree('plan-implement', { notes: false })}

DECOMPOSE (runtime planning): you are the PLANNER for this phase, not its implementer. READ the repo first, then split the work below into the smallest set of items that ONE worker can each finish end-to-end, and declare every item's dependency edges. Plan only — change nothing, commit nothing.

Rules:
- One item = one coherent slice a single worker can own (a module, a handler, a migration step, a document). Never split work that only makes sense as ONE commit; never bundle unrelated work into one item.
- dependsOn lists the ids of the items whose OUTPUT (a decision, an API, a schema, code that must already exist) this item needs. Touching the SAME file is NOT a dependency: every item runs in its OWN worktree on its OWN branch, and the branches are merged afterwards.
- Items with no edge run CONCURRENTLY, so keep the graph as wide and as shallow as the work honestly allows — and never invent parallelism the work does not have. When a real edge is in doubt, declare it.
- prompt is the FULL, self-contained instruction handed VERBATIM to that item's worker: what to change, where, and how to verify it. That text plus the shared goal is all the worker ever sees — none of your reasoning survives.
- If the work genuinely does not decompose, return exactly ONE item covering all of it. That is a normal, cheap answer — never manufacture items to look parallel.
- At most 8 items.

Return items = [ { id, title, prompt, dependsOn } ]: ids are short, unique, kebab tokens, and every dependsOn entry must be one of those ids.

THE WORK TO DECOMPOSE (this phase's goal, verbatim):
${goal}`,
      { label: 'plan:Implement', phase: 'Implement',
        model: 'opus', effort: 'high',
        schema: { type: 'object', additionalProperties: false, required: ["items"], properties: {"items":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["id","title","prompt","dependsOn"],"properties":{"id":{"type":"string"},"title":{"type":"string"},"prompt":{"type":"string"},"dependsOn":{"type":"array","items":{"type":"string"}}}}},"summary":{"type":"string"}} } },
    )
    items = planItems(planned, 'implement', goal)
    results.implementPlan = { items }
    await checkpoint('Implement')
  }
  if (items.length === 1) {
    log('Implement: the plan holds ONE item — running it as a single worker in the run worktree')
    results.implement = await agent(
      `${inWorktree('implement')}

${items[0].prompt}`,
      { label: 'implement', phase: 'Implement', model: 'sonnet',
        schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
    )
  } else {
    const levels = planLevels(items)
    const itemResults = []
    log('Implement: ' + items.length + ' planned item(s) across ' + levels.length + ' dependency level(s)')
    for (let li = 0; li < levels.length; li++) {
      const level = levels[li]
      const itemLines = level.map((it) => `setup_item "${WORKTREE}--${it.slug}" "${BRANCH}--${it.slug}"`).join('\n')
      const itemBranches = level.map((it) => `${BRANCH}--${it.slug}`).join(', ')
      const itemWorktrees = level.map((it) => `${WORKTREE}--${it.slug}`).join(', ')
      const levelSetup = await agent(
        `Create ONE isolated git worktree PER independent work item, each on its OWN branch off ${BRANCH}, so the parallel workers never share a working tree or index. Run from the MAIN repo (do NOT cd into ${WORKTREE}) and create them SEQUENTIALLY — concurrent worktree adds contend on .git locks. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
setup_item() {
  WT="$1"; BR="$2"
  if git worktree list --porcelain | grep -q "/$WT$"; then
    echo "$WT exists — reusing"
  elif git show-ref --verify --quiet "refs/heads/$BR"; then
    git worktree add "$WT" "$BR"
  else
    # Every item branches off the SAME base: the run branch tip ${BRANCH}.
    git worktree add "$WT" -b "$BR" "${BRANCH}"
  fi
  [ -e "$WT/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "$WT/node_modules"
  test -d "$WT" && echo "OK $WT"
}
${itemLines}

Return ready=true ONLY if every per-item worktree exists, plus a short summary.`,
        { label: 'implement:setup-l' + (li + 1), phase: 'Implement',
          model: 'haiku',
          schema: { type: 'object', additionalProperties: false, required: ["ready"], properties: {"ready":{"type":"boolean"},"summary":{"type":"string"}} } },
      )
      if (!levelSetup || !levelSetup.ready) throw new Error('Implement: per-item worktrees not ready for level ' + (li + 1) + ' — ' + ((levelSetup && levelSetup.summary) || ''))
      const levelOut = await parallel(level.map((it) => () => agent(
        `${inItemWorktree(it.slug, WORKTREE + '--' + it.slug, BRANCH + '--' + it.slug)}

CONCURRENCY: sibling workers are executing the OTHER independent work items IN PARALLEL, each in its OWN worktree on its OWN branch — you never share a working tree or index with a sibling, so items may safely touch the same files (an integrate step merges the per-item branches afterwards). Stay strictly inside YOUR OWN worktree: never cd into a sibling's worktree, never rebase, reset, or switch branches, and never run repo-wide destructive git commands — all worktrees share ONE underlying .git, so ref-level operations can still collide (if a git command fails on a transient .git lock, wait a moment and retry; NEVER delete a lock file). Run only your item's targeted checks here, not the full suite — after the integrate step combines the branches, the downstream gates verify the combined result once.

YOUR ITEM (${it.id}) — ${it.title}
${it.prompt}

SHARED GOAL of this phase, for CONTEXT ONLY — implement YOUR item above and nothing else; a sibling worker owns each of the other items, and items you depend on are already merged into your branch point:
${goal}`,
        { label: 'implement:' + it.id, phase: 'Implement', model: 'sonnet',
          schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
      )))
      levelOut.forEach((r, i) => { itemResults.push({ id: level[i].id, title: level[i].title, summary: (r && r.summary) || '' }) })
      const levelIntegrate = await agent(
        `${inWorktree('work-integrate')}

INTEGRATE (combine the parallel fan-out): each independent work item was built on its OWN branch in its OWN worktree. Merge the per-item branches into ${BRANCH} so the downstream gates verify ONE combined diff:

1. In ${WORKTREE} (on ${BRANCH}): confirm a clean tree with 'git status --porcelain'.
2. Merge the per-item branches SEQUENTIALLY, in this order: ${itemBranches}.
   For each: git merge --no-ff <branch> -m "integrate: <branch>". A branch already merged (resumed run) is a no-op — continue.
3. CONFLICT-FIX LOOP: if a merge conflicts, resolve the conflict by hand — the items are independent, so overlaps are mechanical (adjacent edits in the same file, shared import/registration blocks); preserve BOTH sides' intent, then 'git add -A' and commit to complete the merge, and re-run that item's targeted check if one exists. ONLY if a conflict genuinely cannot be resolved without dropping an item's change: 'git merge --abort', record that branch under conflicts, continue with the remaining branches, and return merged=false so the failure is loud instead of an item being silently dropped.
4. After ALL branches are processed, clean up the per-item trees (from the MAIN repo, not inside ${WORKTREE}): for each of ${itemWorktrees} run 'git worktree remove --force <wt>', and delete each fully-merged item branch with 'git branch -d <br>' — keep any UNMERGED (conflicted) branch so its work is not lost.
5. Sanity: the working tree is clean and 'git log --oneline -n 20' on ${BRANCH} shows the integrate merges.

Return merged=true ONLY if EVERY per-item branch landed in ${BRANCH}, the list of conflicted branches (empty when clean), and a short summary.`,
        { label: 'implement:integrate-l' + (li + 1), phase: 'Implement',
          model: 'opus', effort: 'high',
          schema: { type: 'object', additionalProperties: false, required: ["merged"], properties: {"merged":{"type":"boolean"},"conflicts":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
      )
      if (!levelIntegrate || !levelIntegrate.merged) throw new Error('Implement: level ' + (li + 1) + ' did not integrate into ' + BRANCH + ' — ' + ((levelIntegrate && levelIntegrate.summary) || ''))
    }
    results.implement = { summary: 'plan fan-out: ' + items.length + ' item(s) across ' + levels.length + ' dependency level(s)', items: itemResults }
  }
  done.add('Implement')
  await checkpoint('Implement')
}

phase('Verify')
if (done.has('Verify')) {
  log('Verify already complete (resumed)')
} else {
  results.verify = await agent(
    `${inWorktree('verify')}

VERIFY (GREEN): run the full relevant test suite for the changes on ${BRANCH} vs ${BASE || 'the base branch'} (Jest unit + any tryve E2E from RED). EVERYTHING must pass. If any test fails, the implementation is incomplete — STOP and report which failed; do NOT weaken tests to pass.`,
    { label: 'verify', phase: 'Verify', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["green"], properties: {"green":{"type":"boolean"},"failing":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.verify || !results.verify.green) throw new Error('Verify failed: not green — ' + (results.verify && (results.verify.failing || []).join(', ')))
  done.add('Verify')
  await checkpoint('Verify')
}

phase('PathGap')
if (done.has('PathGap')) {
  log('PathGap already complete (resumed)')
} else {
  // Close test gaps for code paths the ACs never specified (decide-or-justify, hard-fail).
  let passed = false, last = null
  for (let round = 1; round <= 3 && !passed; round++) {
    const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
    last = await agent(
      `${inWorktree('pathgap')}

PATH-GAP: the ACs do NOT cover every code path. Steps:
1. Run Jest with BRANCH coverage; intersect with the CHANGED lines (git diff vs ${BASE || 'the base branch'}) to find uncovered branches introduced by this change.
2. For EACH uncovered changed branch, do ONE: (a) add a unit/integration test that meaningfully exercises AND asserts it, or (b) if it is genuinely unreachable/defensive, record an explicit justification in implementation-notes/pathgap.html.
3. Re-run coverage. There must be NO silent gaps — every uncovered changed branch is either tested or justified.
Do NOT delete/alter source branches just to raise coverage. Commit new tests + notes.` + carry,
      { label: `pathgap:r${round}`, phase: 'PathGap', model: 'opus', effort: 'high',
        schema: { type: 'object', additionalProperties: false, required: ["closed"], properties: {"closed":{"type":"boolean"},"uncovered":{"type":"number"},"tested":{"type":"number"},"justified":{"type":"number"},"summary":{"type":"string"}} } },
    )
    passed = last && last.closed
  }
  if (!passed) throw new Error('PathGap failed: uncovered changed-code branches remain after 3 rounds — ' + (last && last.summary || ''))
  results.pathGap = last
  done.add('PathGap')
  await checkpoint('PathGap')
}

phase('CodeGate')
if (done.has('CodeGate')) {
  log('CodeGate already complete (resumed)')
} else {
  // Panel review: guard → parallel dimensions → dedup → confidence filter → lead fixer.
  const guard = await agent(
    `${inWorktree('codegate-guard', { notes: false })}

Inspect the diff of ${BRANCH} vs ${BASE || 'the base branch'} (git diff in ${WORKTREE}). Is this a CODE change (source/test code — not solely docs, config, comments, or generated artifacts)? Return isCode and a one-line reason. Do NOT edit anything.`,
    { label: 'codegate:guard', phase: 'CodeGate', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["isCode"], properties: {"isCode":{"type":"boolean"},"reason":{"type":"string"}} } },
  )
  if (!guard || !guard.isCode) {
    log('CodeGate: not a code change (' + ((guard && guard.reason) || 'no reason') + ') — panel skipped')
    results.codeGate = { gatePassed: true, skipped: true, critical: 0, high: 0, summary: 'skipped: not a code change' }
  } else {
    const DIMENSIONS = [{"key":"bugs","focus":"Correctness: shallow-scan the diff itself for real bugs — logic errors, off-by-one, broken contracts, null/undefined misuse. Focus on the changed lines; skip nitpicks a senior engineer would not raise and anything a linter/typechecker would catch."},{"key":"security","focus":"Security on the CHANGED paths only: injection, missing authz/authn, secrets committed, unsafe deserialization, path traversal, SSRF."},{"key":"reuse","focus":"Reuse & simplification: duplicated logic, existing helpers/utilities the change should have used, dead code introduced, needless complexity."},{"key":"conventions","focus":"Conventions: violations of CLAUDE.md guidance (repo root + every directory the diff touches) and of guidance in code comments adjacent to the changes. Cite the exact guidance line for every finding."},{"key":"history","focus":"Git history: read git blame/log for the modified code; flag changes that contradict the reason a prior fix was made or reintroduce a previously-fixed bug. Cite the commit."}]
    const rawResults = await parallel(DIMENSIONS.map((d) => () => agent(
      `${inWorktree('codegate-' + d.key, { notes: false })}

READ-ONLY panel review of the changes on ${BRANCH} vs ${BASE || 'the base branch'} (git diff in ${WORKTREE}) — do NOT edit or fix anything; you only report findings.
DIMENSION — ${d.focus}
Return findings with exact repo-relative file + line + severity (Critical|High|Medium|Low) + title + detail. No findings is a valid answer.`,
      { label: 'codegate:' + d.key, phase: 'CodeGate', model: 'opus', effort: 'high',
        schema: { type: 'object', additionalProperties: false, required: ["findings"], properties: {"findings":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["file","line","severity","title"],"properties":{"file":{"type":"string"},"line":{"type":"number"},"severity":{"type":"string","enum":["Critical","High","Medium","Low"]},"title":{"type":"string"},"detail":{"type":"string"}}}}} } },
    )))
    const all = rawResults.filter(Boolean).flatMap((r) => r.findings || [])
    const seen = new Set()
    const deduped = []
    for (const f of all) {
      const k = (f.file || '') + ':' + (f.line || 0)
      if (!seen.has(k)) { seen.add(k); deduped.push(f) }
    }
    const scored = deduped.length ? await parallel(deduped.map((f, i) => () => agent(
      `${inWorktree('codegate-score-' + i, { notes: false })}

Verify ONE code-review finding against the actual code (read the files; do NOT edit).
FINDING (JSON): ${JSON.stringify(f)}
Score 0-100 how confident you are the finding is REAL and WORTH FIXING:
- 0: Not confident at all. False positive that does not stand up to light scrutiny, or a pre-existing issue.
- 25: Somewhat confident. Might be real, might be a false positive; could not verify.
- 50: Moderately confident. Verified real, but may be a nitpick or rarely hit in practice.
- 75: Highly confident. Double-checked and verified: very likely real, will be hit in practice, directly impacts functionality (or is explicitly required by CLAUDE.md).
- 100: Absolutely certain. Double-checked, definitely real, will happen frequently; evidence directly confirms it.
Automatic false positives (score 0): pre-existing issues; linter/typechecker/compiler-catchable; pedantic nitpicks; issues on lines the diff did not modify; intentional changes related to the goal.
Return the score and a one-line reason.`,
      { label: 'codegate:score-' + i, phase: 'CodeGate', model: 'haiku',
        schema: { type: 'object', additionalProperties: false, required: ["score"], properties: {"score":{"type":"number"},"reason":{"type":"string"}} } },
    ).then((v) => ({ ...f, confidence: v ? v.score : 0 })))) : []
    const confirmed = scored.filter(Boolean).filter((f) => f.confidence >= 80)
    if (!confirmed.length) {
      log('CodeGate panel: 0 of ' + all.length + ' raw findings survived verification — passing')
      results.codeGate = { gatePassed: true, critical: 0, high: 0, summary: 'panel: ' + all.length + ' raw, 0 confirmed', panel: { raw: all.length, deduped: deduped.length, confirmed: 0 } }
    } else {
      let passed = false, last = null
      for (let round = 1; round <= 3 && !passed; round++) {
        const dod = results.brief ? `\n\nScope this gate to the task's actual goal — judge findings against what the task set out to achieve; do NOT drift into changes unrelated to it.\nGOAL: ${results.brief.goal || '(none)'}` + ((results.brief.acceptanceCriteria || []).length ? `\nACCEPTANCE CRITERIA:\n- ${results.brief.acceptanceCriteria.join('\n- ')}` : '') : ''
        const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
        last = await agent(
          `${inWorktree('codegate-lead')}

You are the review-panel LEAD for the changes on ${BRANCH} vs ${BASE || 'the base branch'}. The confirmed findings (confidence >= 80) from the parallel panel are below. Rank them; FIX every Critical and High in the worktree; run the project build/lint (it MUST pass); re-run it after fixes and commit. Fix a Medium or Low finding ONLY when the fix is trivial and zero-risk; otherwise leave it untouched and record it in the knownOpen output array (its exact file, line, severity, title) — a confirmed Medium/Low below the fix bar is NOT wrong, so it must stay known-open for the human, never silently dropped; knownOpen is empty when none remain. You may skip a finding ONLY with an explicit reason it is wrong — record EVERY skipped finding in the skippedFindings output array (its title plus your reason), empty when you skipped none; this is the audit trail a human reviews.
OUTPUT CONTRACT: return gatePassed=true ONLY if every Critical and High finding is fixed or skipped-with-explicit-reason AND the build/lint passes; report critical and high as the counts of findings of each severity left UNRESOLVED after your fixes (both 0 when gatePassed=true).
EVIDENCE: report the exact build/lint command you ran as buildCmd and its numeric exit code as buildExit; if the project has no build/lint, run the closest verification command (e.g. the test suite) and report that instead. The gate rejects gatePassed=true unless buildExit is 0.

FINDINGS (JSON): ${JSON.stringify(confirmed)}` + dod + carry,
          { label: `codegate:lead-r${round}`, phase: 'CodeGate', agentType: 'lirbox:lirbox-code-reviewer', model: 'opus', effort: 'high',
            schema: { type: 'object', additionalProperties: false, required: ["gatePassed","critical","high","buildCmd","buildExit","skippedFindings","knownOpen"], properties: {"gatePassed":{"type":"boolean"},"critical":{"type":"number"},"high":{"type":"number"},"summary":{"type":"string"},"buildCmd":{"type":"string"},"buildExit":{"type":"number"},"skippedFindings":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["title","reason"],"properties":{"title":{"type":"string"},"reason":{"type":"string"}}}},"knownOpen":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["file","line","severity","title"],"properties":{"file":{"type":"string"},"line":{"type":"number"},"severity":{"type":"string"},"title":{"type":"string"}}}}} } },
        )
        passed = last && last.gatePassed && last.buildExit === 0
      }
      if (!passed) throw new Error('CodeGate failed: unresolved Critical/High after 3 rounds — ' + (last && last.summary || ''))
      results.codeGate = { ...last, panel: { raw: all.length, deduped: deduped.length, confirmed: confirmed.length } }
    }
  }
  done.add('CodeGate')
  await checkpoint('CodeGate')
}

phase('ReVerify')
if (done.has('ReVerify')) {
  log('ReVerify already complete (resumed)')
} else {
  results.reVerify = await agent(
    `${inWorktree('reverify')}

RE-VERIFY: after IMPROVE/SIMPLIFY (CodeGate), re-run the FULL test suite + branch coverage for the changes on ${BRANCH} vs ${BASE || 'the base branch'}. Everything green before must STILL be green and coverage must not have regressed. If a refactor broke anything, STOP and report; do NOT weaken tests.`,
    { label: 'reverify', phase: 'ReVerify', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["green"], properties: {"green":{"type":"boolean"},"regressions":{"type":"array","items":{"type":"string"}},"summary":{"type":"string"}} } },
  )
  if (!results.reVerify || !results.reVerify.green) throw new Error('ReVerify failed: regression after improve/simplify — ' + (results.reVerify && (results.reVerify.regressions || []).join(', ')))
  done.add('ReVerify')
  await checkpoint('ReVerify')
}

phase('DocsGate')
if (done.has('DocsGate')) {
  log('DocsGate already complete (resumed)')
} else {
  results.docs = await agent(
    `${inWorktree('docsgate')}

Write an implementation summary for the changes on ${BRANCH} vs ${BASE || 'the base branch'} into docs/changes/${NAME}/summary.md with proper frontmatter (mkdir -p the dir). Read the diff, the goal${TICKET ? ' and ticket ' + TICKET : ''}, and ALL fragments in the implementation-notes/ directory — fold their design decisions / deviations / tradeoffs / open questions into the summary. Commit it.`,
    { label: 'docs', phase: 'DocsGate', agentType: 'lirbox:lirbox-docs-writer', model: 'opus', effort: 'high',
      schema: { type: 'object', additionalProperties: false, required: ["written"], properties: {"written":{"type":"boolean"},"docPath":{"type":"string"}} } },
  )
  if (!results.docs || !results.docs.written) throw new Error('DocsGate failed: no implementation summary written')
  done.add('DocsGate')
  await checkpoint('DocsGate')
}

phase('DoDGate')
if (done.has('DoDGate')) {
  log('DoDGate already complete (resumed)')
} else {
  let dodPassed = false, dodLast = null, dodStalled = false, prevUnmetKey = null
  const dodUnmet = () => ((dodLast && dodLast.criteria) || []).filter((c) => c.verdict !== 'MET')
  for (let attempt = 1; attempt <= DOD_MAX_ATTEMPTS && !dodPassed && !dodStalled; attempt++) {
    if (attempt > 1) {
      // Replan on gate failure: new plan from the EXECUTED unmet verdicts, then execute it.
      const unmet = dodUnmet()
      results.dodReplan = await agent(
        `${inWorktree('dodgate-replan')}

DoD REPLAN (attempt ${attempt}/${DOD_MAX_ATTEMPTS}) — PLAN ONLY, do NOT edit code in this step. The in-phase fix rounds could not close the unmet definition-of-done criteria below; patching the current approach harder is not working. Produce a NEW plan version:
- Diagnose WHY each unmet criterion still fails, from the EXECUTED check output / cited evidence below. These verdicts came from actually running the checks — they are the only routing input; worker self-reports are untrusted claims and can never override them.
- Write a revised, ordered, concrete step list that CHANGES APPROACH where the old one failed (different design, different files, different strategy). Descoping is NOT allowed — every criterion must still end up MET; do not weaken, game, or delete any check.

UNMET CRITERIA + EXECUTED CHECK OUTPUT (JSON): ${JSON.stringify(unmet)}
FULL DoD (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
        { label: `dodgate:replan-a${attempt}`, phase: 'DoDGate', model: 'opus', effort: 'high',
          schema: { type: 'object', additionalProperties: false, required: ["plan","steps"], properties: {"plan":{"type":"string"},"steps":{"type":"array","items":{"type":"string"}}} } },
      )
      await agent(
        `${inWorktree('dodgate-execute')}

DoD EXECUTE (attempt ${attempt}/${DOD_MAX_ATTEMPTS}): carry out the revised plan below IN FULL — implement it, run each unmet criterion's relevant checks yourself, re-run the project test suite (your changes must not regress it), and commit. Do NOT weaken, game, or delete a check; if a step proves impossible, say so in the summary instead of faking it. The DoD verify worker re-adjudicates afterwards — only executed check results count, never your own report.

REVISED PLAN (JSON): ${JSON.stringify(results.dodReplan)}
UNMET CRITERIA (JSON): ${JSON.stringify(unmet)}
FULL DoD (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
        { label: `dodgate:execute-a${attempt}`, phase: 'DoDGate', model: 'sonnet',
          schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
      )
    }
    for (let round = 1; round <= 3 && !dodPassed; round++) {
      dodLast = await agent(
        `${inWorktree('dodgate-verify', { notes: false })}

DoD VERIFY (round ${round}/3) — MEASURE ONLY, do NOT fix anything. Adjudicate EVERY criterion below against the work on ${BRANCH} vs ${BASE || 'the base branch'}:
- tier "checkable": run the "check" command inside ${WORKTREE}; exit 0 = MET, non-zero = UNMET; the command output is the evidence.
- tier "judged": verify against the ACTUAL diff and artifacts in ${WORKTREE} — inspect the real code/files changed on ${BRANCH} (e.g. git diff, reading the touched files) and CITE artifact evidence (file:line, command output, test result). Worker reports and implementation-notes are UNTRUSTED claims: they can point you at evidence but can NEVER satisfy a criterion by themselves. No artifact evidence = UNMET. If a criterion's implementation was deferred/descoped without a recorded human decision in the DoD file, score it UNMET — a deferral is a failing verdict, never a pass.
Verdicts: MET | UNMET | PARTIAL.

CRITERIA (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
        { label: `dodgate:verify-a${attempt}-r${round}`, phase: 'DoDGate', model: 'opus', effort: 'high',
          schema: { type: 'object', additionalProperties: false, required: ["criteria"], properties: {"criteria":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["id","verdict","evidence"],"properties":{"id":{"type":"string"},"verdict":{"type":"string","enum":["MET","UNMET","PARTIAL"]},"evidence":{"type":"string"}}}}} } },
      )
      const unmet = dodUnmet()
      dodPassed = !!(dodLast && (dodLast.criteria || []).length && unmet.length === 0)
      if (!dodPassed && round < 3) {
        await agent(
          `${inWorktree('dodgate-fix')}

DoD FIX (round ${round}/3): the definition-of-done criteria below are NOT met. Make them met — implement what is missing, run the relevant checks yourself, then re-run the project test suite (your fix must not regress it) and commit. Do NOT weaken, game, or delete a check; if a criterion is genuinely impossible, say so in the summary instead of faking it.

UNMET (JSON): ${JSON.stringify(unmet)}
FULL DoD (JSON): ${JSON.stringify(DOD_CRITERIA)}`,
          { label: `dodgate:fix-a${attempt}-r${round}`, phase: 'DoDGate', model: 'sonnet',
            schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"},"fixed":{"type":"array","items":{"type":"string"}}} } },
        )
      }
    }
    if (!dodPassed) {
      // Stall detection: unmet-id set unchanged between consecutive gate runs → replanning is
      // not converging; stop early instead of burning the remaining attempts.
      const unmetKey = dodUnmet().map((c) => c.id).sort().join(',')
      if (prevUnmetKey !== null && unmetKey === prevUnmetKey) {
        dodStalled = true
        log('DoDGate: stall detected — unmet set unchanged between gate runs (' + unmetKey + ')')
      }
      prevUnmetKey = unmetKey
    }
  }
  results.dodGate = dodLast
  if (!dodPassed) {
    // Escalate, never just die: persist status 'escalated' + the unmet list to durable state
    // (same startedAt-preserving write as checkpoint) so a human or resume can pick it up.
    const payload = JSON.stringify(
      { workflow: NAME, status: 'escalated', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, dod: { criteria: DOD_CRITERIA }, unmet: dodUnmet(), phasesDone: [...done], results },
      null, 2,
    )
    await agent(
      `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
      { label: 'dodgate:escalate', phase: 'DoDGate', model: 'haiku',
        schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
    )
    throw new Error('DoDGate escalated: DoD not fully met (' + (dodStalled ? 'stalled — unmet set unchanged' : DOD_MAX_ATTEMPTS + ' attempts exhausted') + ') — unmet: ' + dodUnmet().map((c) => c.id).join(', '))
  }
  done.add('DoDGate')
  await checkpoint('DoDGate')
}

phase('Writeup')
if (done.has('Writeup')) {
  log('Writeup already complete (resumed)')
} else {
  results.writeup = await agent(
    `${inWorktree('writeup', { notes: false })}

Produce reviewer-facing delivery artifacts for the changes on ${BRANCH} vs ${BASE || 'the base branch'}, all COMMITTED under docs/changes/${NAME}/ in the worktree so they ride the PR:
1. PRESERVE design notes — mkdir -p docs/changes/${NAME}/notes, then copy every implementation-notes/*.html into it (if any exist). These are the per-worker decision notes; keep them, do NOT discard. If implementation-notes/frontend-evidence/ exists, ALSO copy it recursively — manifest.json, screenshots, logs, every file type — into docs/changes/${NAME}/evidence/ so the frontend evidence rides the PR.
2. WRITE-UP — invoke the lirbox:pr-writeup skill (via the Skill tool, by name) to produce a self-contained reviewer write-up of this branch's diff; save it to docs/changes/${NAME}/writeup.html. If the Skill tool is unavailable, read plugins/lirbox/skills/pr-writeup/SKILL.md + assets/template.html and follow them.
3. DESIGN DIAGRAM — invoke the lirbox:flowchart skill (via the Skill tool, by name) to visualize the design of this change; choose the Mermaid diagram type (flowchart OR sequenceDiagram) that best fits; save to docs/changes/${NAME}/design.html. The flowchart skill validates its own output — ensure that validation passes before continuing. If the Skill tool is unavailable, read plugins/lirbox/skills/flowchart/SKILL.md + assets/template.html, follow them, and run that skill's assets/validate.mjs on the result.
4. COMMIT all of docs/changes/${NAME}/ on ${BRANCH}.
Return what was written.`,
    { label: 'writeup', phase: 'Writeup', model: 'opus', effort: 'high',
      schema: { type: 'object', additionalProperties: false, required: ["written"], properties: {"written":{"type":"boolean"},"writeupPath":{"type":"string"},"designPath":{"type":"string"},"notesPreserved":{"type":"number"}} } },
  )
  if (!results.writeup || !results.writeup.written) throw new Error('Writeup failed: reviewer artifacts not written under docs/changes/')
  done.add('Writeup')
  await checkpoint('Writeup')
}

phase('PR')
if (done.has('PR')) {
  log('PR already complete (resumed)')
} else {
  results.pr = await agent(
    `${inWorktree('pr', { notes: false })}

Push the branch and open a PR with the GitHub CLI:
git push -u origin ${BRANCH}
gh pr create --base ${BASE || 'main'} --head ${BRANCH} --title "TODO title" --body "TODO summary. Reviewer artifacts are committed under docs/changes/snap/ — link writeup.html, design.html, and notes/ in the PR body${TICKET ? '; refs ' + TICKET : ''}"
Include a "## Definition of done" section in the PR body — headline "DoD: <met>/<total> MET", then one line per criterion (id, verdict, evidence) from this JSON: ${JSON.stringify((results.dodGate && results.dodGate.criteria) || [])}
If a PR for this branch already exists, return its URL instead of erroring.`,
    { label: 'pr', phase: 'PR', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["prUrl"], properties: {"prUrl":{"type":"string"}} } },
  )
  done.add('PR')
  await checkpoint('PR')
}

phase('TicketUpdate')
if (!TICKET) {
  log('No ticket — nothing to update')
} else if (done.has('TicketUpdate')) {
  log('TicketUpdate already complete (resumed)')
} else {
  results.ticketUpdate = await agent(
    `Update tracker ticket ${TICKET}. Use ToolSearch to load the tracker tools.
Jira: getTransitionsForJiraIssue → transitionJiraIssue to the review state (match name case-insensitively; skip if none) → addCommentToJiraIssue with the PR link ${results.pr && results.pr.prUrl}.
Linear: use the Linear MCP update/comment tools instead, ONLY if connected.`,
    { label: 'ticket-update', phase: 'TicketUpdate', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ["updated"], properties: {"updated":{"type":"boolean"},"transition":{"type":"string"}} } },
  )
  done.add('TicketUpdate')
  await checkpoint('TicketUpdate')
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results }
