// AUTO-GENERATED by scaffold-workflow.cjs — do NOT hand-edit.
// Work-phase prompts come from --prompt/--prompts-file (data-in). To change a prompt OR the
// structure, re-run the generator with --force. A leftover \`TODO:\` means a prompt wasn't
// supplied — fill it by regenerating, not by editing this file.
//
// Conductor rules: pure JS only — no fs/git, no Date.now()/Math.random().
// All side-effects happen inside agent() subagents.
//
// Resume semantics: phases are AT-LEAST-ONCE on resume. We checkpoint AFTER the
// side-effect, so a crash between side-effect and checkpoint re-runs that phase.
// Every phase MUST therefore be idempotent. phasesDone is trusted only after the
// entry guard below validates it is a contiguous prefix of the phase order.

export const meta = {
  name: 'snap',
  description: 'Durable workflow: snap',
  phases: [
    { title: 'Setup' },
    { title: 'Work' },
  ],
}

// Some Workflow harnesses deliver `args` as a JSON STRING rather than an object; normalize
// once here (BEFORE any args read) so every `(args && args.X)` guard below works either way.
// Uses only typeof + JSON.parse — both allowed at the restricted conductor layer.
if (typeof args === 'string') args = JSON.parse(args)

const NAME     = 'snap'
const STATE    = `.workflows/state/${NAME}.json`
const BRANCH   = (args && args.branch) ? args.branch : `wf/${NAME}`
const BASE     = (args && args.base) ? args.base : ''
const WORKTREE = `.worktrees/${NAME}`
const TICKET   = (args && args.ticket) ? args.ticket : null

const prior = (args && args.results) ? args.results : {}
const done  = new Set((args && args.phasesDone) ? args.phasesDone : [])
const results = { ...prior }

// --- Resume reachability guard: phasesDone MUST be a contiguous prefix ---
// Canonical order is baked in as a literal — the Workflow runtime consumes `meta` as
// metadata, so it is NOT a runtime binding in this body. A durable state that marks a
// phase done while an earlier phase is not is unreachable (corrupt/forged) — reject it
// loudly instead of silently skipping required setup work.
;(() => {
  const order = ["Setup","Work"]
  for (const title of done) {
    if (!order.includes(title)) {
      throw new Error(`Unreachable resume: phasesDone has unknown phase '${title}' (not in order: ${order.join(' → ')})`)
    }
  }
  // Walk the order; once we hit the first NOT-done phase, no later phase may be done.
  let seenGap = false
  for (const title of order) {
    if (done.has(title)) {
      if (seenGap) {
        throw new Error(`Unreachable resume: phase '${title}' is done but an earlier required phase is not — phasesDone must be a contiguous prefix of [${order.join(' → ')}], got [${[...done].join(', ')}]`)
      }
    } else {
      seenGap = true
    }
  }
})()

// Per-worker instruction. `slot` makes the notes file UNIQUE so parallel / multiple agents
// never clobber each other. For a parallel fan-out, pass a slot unique per item (e.g. `phase-${i}`).
// Pass { notes: false } for mechanical steps (PR push, etc.) that make no design decisions —
// they should NOT create a notes file at all. Where notes ARE offered they are judgment-gated:
// write one ONLY if there is something a reviewer genuinely needs.
function inWorktree(slot, opts) {
  const base = `Work ONLY inside the git worktree at ${WORKTREE} (run \`cd ${WORKTREE}\` first; it is on ` +
    `branch ${BRANCH}). Do NOT edit any file outside ${WORKTREE}. Commit your changes there.`
  if (opts && opts.notes === false) return base
  return base + `\n\nIf — and ONLY if — this step involved a non-trivial design decision, an ` +
    `intentional deviation from the spec, a tradeoff between real alternatives, or an open question a ` +
    `reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/${slot}.html ` +
    `in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or ` +
    `no-decision work, SKIP the file — do not create empty or boilerplate notes.`
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first.
async function checkpoint(phaseTitle) {
  const payload = JSON.stringify(
    { workflow: NAME, status: 'running', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results },
    null, 2,
  )
  await agent(
    `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
    { label: `checkpoint:${phaseTitle}`, phase: phaseTitle, model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
phase('Setup')
if (done.has('Setup')) {
  log('Setup already complete (resumed)')
} else {
  results.setup = await agent(
    `Create an isolated git worktree. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/${WORKTREE}$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "${WORKTREE}" "${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="${BASE}"
  # Auto-detect the remote's default branch when no --base was given.
  [ -n "$BASEREF" ] || BASEREF="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/$BASEREF"; then
    START="origin/$BASEREF"
  elif [ -n "$BASEREF" ]; then
    echo "WARN: origin/$BASEREF not found — branching from local $BASEREF (may be stale)"; START="$BASEREF"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching ${BRANCH} from $START"
  git worktree add "${WORKTREE}" -b "${BRANCH}" "$START"
fi
[ -e "${WORKTREE}/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "${WORKTREE}/node_modules"
test -d "${WORKTREE}" && echo OK`,
    { label: 'setup:worktree', phase: 'Setup', model: 'haiku',
      schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
  )
  done.add('Setup')
  await checkpoint('Setup')
}

phase('Work')
if (done.has('Work')) {
  log('Work already complete (resumed)')
} else {
  results.work = await agent(
    `${inWorktree('Work')}

Apply the change described in the run brief.`,
    { label: 'work', phase: 'Work', model: 'sonnet',
      schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Work')
  await checkpoint('Work')
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results }
