// AUTO-GENERATED by scaffold-workflow.cjs — do NOT hand-edit.
// Work-phase prompts come from --prompt/--prompts-file (data-in). To change a prompt OR the
// structure, re-run the generator with --force. A leftover \`TODO:\` means a prompt wasn't
// supplied — fill it by regenerating, not by editing this file.
//
// Conductor rules: pure JS only — no fs/git, no Date.now()/Math.random().
// All side-effects happen inside agent() subagents.
//
// Resume semantics: phases are AT-LEAST-ONCE on resume. We checkpoint AFTER the
// side-effect, so a crash between side-effect and checkpoint re-runs that phase.
// Every phase MUST therefore be idempotent. phasesDone is trusted only after the
// entry guard below validates it is a contiguous prefix of the phase order.

export const meta = {
  name: 'snap',
  description: 'Durable workflow: snap',
  phases: [
    { title: 'Setup' },
    { title: 'Work' },
    { title: 'CodeGate' },
  ],
}

// Some Workflow harnesses deliver `args` as a JSON STRING rather than an object; normalize
// once here (BEFORE any args read) so every `(args && args.X)` guard below works either way.
// Uses only typeof + JSON.parse — both allowed at the restricted conductor layer.
if (typeof args === 'string') args = JSON.parse(args)

const NAME     = 'snap'
const STATE    = `.workflows/state/${NAME}.json`
const BRANCH   = (args && args.branch) ? args.branch : `wf/${NAME}`
const BASE     = (args && args.base) ? args.base : ''
const WORKTREE = `.worktrees/${NAME}`
const TICKET   = (args && args.ticket) ? args.ticket : null

const prior = (args && args.results) ? args.results : {}
const done  = new Set((args && args.phasesDone) ? args.phasesDone : [])
const results = { ...prior }

// --- Resume reachability guard: phasesDone MUST be a contiguous prefix ---
// Canonical order is baked in as a literal — the Workflow runtime consumes `meta` as
// metadata, so it is NOT a runtime binding in this body. A durable state that marks a
// phase done while an earlier phase is not is unreachable (corrupt/forged) — reject it
// loudly instead of silently skipping required setup work.
;(() => {
  const order = ["Setup","Work","CodeGate"]
  for (const title of done) {
    if (!order.includes(title)) {
      throw new Error(`Unreachable resume: phasesDone has unknown phase '${title}' (not in order: ${order.join(' → ')})`)
    }
  }
  // Walk the order; once we hit the first NOT-done phase, no later phase may be done.
  let seenGap = false
  for (const title of order) {
    if (done.has(title)) {
      if (seenGap) {
        throw new Error(`Unreachable resume: phase '${title}' is done but an earlier required phase is not — phasesDone must be a contiguous prefix of [${order.join(' → ')}], got [${[...done].join(', ')}]`)
      }
    } else {
      seenGap = true
    }
  }
})()

// Per-worker instruction. `slot` makes the notes file UNIQUE so parallel / multiple agents
// never clobber each other. For a parallel fan-out, pass a slot unique per item (e.g. `phase-${i}`).
// Pass { notes: false } for mechanical steps (PR push, etc.) that make no design decisions —
// they should NOT create a notes file at all. Where notes ARE offered they are judgment-gated:
// write one ONLY if there is something a reviewer genuinely needs.
function inWorktree(slot, opts) {
  const base = `Work ONLY inside the git worktree at ${WORKTREE} (run \`cd ${WORKTREE}\` first; it is on ` +
    `branch ${BRANCH}). Do NOT edit any file outside ${WORKTREE}. Commit your changes there.`
  if (opts && opts.notes === false) return base
  return base + `\n\nIf — and ONLY if — this step involved a non-trivial design decision, an ` +
    `intentional deviation from the spec, a tradeoff between real alternatives, or an open question a ` +
    `reviewer must confirm, append it to a notes file UNIQUE to you at implementation-notes/${slot}.html ` +
    `in the worktree (mkdir -p the dir; create if missing; APPEND — never clobber). For mechanical or ` +
    `no-decision work, SKIP the file — do not create empty or boilerplate notes.`
}

// startedAt-preserving merge: cat clobbers the file, so read prev startedAt first.
async function checkpoint(phaseTitle) {
  const payload = JSON.stringify(
    { workflow: NAME, status: 'running', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results },
    null, 2,
  )
  await agent(
    `Persist durable workflow state to the MAIN repo (do NOT cd into the worktree). Run EXACTLY:

mkdir -p .workflows/state
cat > .workflows/state/.${NAME}.payload.json <<'DURABLE_JSON'
${payload}
DURABLE_JSON
node -e "const fs=require('fs');const f='${STATE}';const p='.workflows/state/.${NAME}.payload.json';let prev={};try{prev=JSON.parse(fs.readFileSync(f,'utf8'))}catch(e){};const s=JSON.parse(fs.readFileSync(p,'utf8'));const n=new Date().toISOString();s.startedAt=prev.startedAt||n;s.updatedAt=n;fs.writeFileSync(f,JSON.stringify(s,null,2));fs.unlinkSync(p)"
node -e "JSON.parse(require('fs').readFileSync('${STATE}','utf8'))" && echo OK

Return whether the file was written and parses.`,
    { label: `checkpoint:${phaseTitle}`, phase: phaseTitle,
      schema: { type: 'object', additionalProperties: false, required: ['written'], properties: { written: { type: 'boolean' }, path: { type: 'string' } } } },
  )
}

// --- Setup: create/reuse worktree + symlink node_modules (worktrees don't carry it) ---
phase('Setup')
if (done.has('Setup')) {
  log('Setup already complete (resumed)')
} else {
  results.setup = await agent(
    `Create an isolated git worktree. Run idempotently:

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || { echo "ERROR: not a git repo"; exit 1; }
ROOT="$(git rev-parse --show-toplevel)"
if git worktree list --porcelain | grep -q "/${WORKTREE}$"; then
  echo "worktree exists — reusing"
elif git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "${WORKTREE}" "${BRANCH}"
else
  # Branch from the FRESH remote tip, not a possibly-stale local ref.
  git fetch origin --quiet 2>/dev/null || echo "WARN: git fetch origin failed — using local refs (may be stale)"
  BASEREF="${BASE}"
  # Auto-detect the remote's default branch when no --base was given.
  [ -n "$BASEREF" ] || BASEREF="$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##')"
  if [ -n "$BASEREF" ] && git show-ref --verify --quiet "refs/remotes/origin/$BASEREF"; then
    START="origin/$BASEREF"
  elif [ -n "$BASEREF" ]; then
    echo "WARN: origin/$BASEREF not found — branching from local $BASEREF (may be stale)"; START="$BASEREF"
  else
    echo "WARN: could not detect remote default branch — branching from current HEAD (may be stale)"; START="HEAD"
  fi
  echo "Branching ${BRANCH} from $START"
  git worktree add "${WORKTREE}" -b "${BRANCH}" "$START"
fi
[ -e "${WORKTREE}/node_modules" ] || [ ! -d "$ROOT/node_modules" ] || ln -s "$ROOT/node_modules" "${WORKTREE}/node_modules"
test -d "${WORKTREE}" && echo OK`,
    { label: 'setup:worktree', phase: 'Setup',
      schema: { type: 'object', additionalProperties: false, required: ['ready'], properties: { ready: { type: 'boolean' }, worktree: { type: 'string' }, branch: { type: 'string' } } } },
  )
  done.add('Setup')
  await checkpoint('Setup')
}

phase('Work')
if (done.has('Work')) {
  log('Work already complete (resumed)')
} else {
  results.work = await agent(
    `${inWorktree('Work')}

Apply the change described in the run brief.`,
    { label: 'work', phase: 'Work', schema: { type: 'object', additionalProperties: false, required: ["summary"], properties: {"summary":{"type":"string"}} } },
  )
  done.add('Work')
  await checkpoint('Work')
}

phase('CodeGate')
if (done.has('CodeGate')) {
  log('CodeGate already complete (resumed)')
} else {
  // Panel review: guard → parallel dimensions → dedup → confidence filter → lead fixer.
  const guard = await agent(
    `${inWorktree('codegate-guard', { notes: false })}

Inspect the diff of ${BRANCH} vs ${BASE || 'the base branch'} (git diff in ${WORKTREE}). Is this a CODE change (source/test code — not solely docs, config, comments, or generated artifacts)? Return isCode and a one-line reason. Do NOT edit anything.`,
    { label: 'codegate:guard', phase: 'CodeGate',
      schema: { type: 'object', additionalProperties: false, required: ["isCode"], properties: {"isCode":{"type":"boolean"},"reason":{"type":"string"}} } },
  )
  if (!guard || !guard.isCode) {
    log('CodeGate: not a code change (' + ((guard && guard.reason) || 'no reason') + ') — panel skipped')
    results.codeGate = { gatePassed: true, skipped: true, critical: 0, high: 0, summary: 'skipped: not a code change' }
  } else {
    const DIMENSIONS = [{"key":"bugs","focus":"Correctness: shallow-scan the diff itself for real bugs — logic errors, off-by-one, broken contracts, null/undefined misuse. Focus on the changed lines; skip nitpicks a senior engineer would not raise and anything a linter/typechecker would catch."},{"key":"security","focus":"Security on the CHANGED paths only: injection, missing authz/authn, secrets committed, unsafe deserialization, path traversal, SSRF."},{"key":"reuse","focus":"Reuse & simplification: duplicated logic, existing helpers/utilities the change should have used, dead code introduced, needless complexity."},{"key":"conventions","focus":"Conventions: violations of CLAUDE.md guidance (repo root + every directory the diff touches) and of guidance in code comments adjacent to the changes. Cite the exact guidance line for every finding."}]
    const rawResults = await parallel(DIMENSIONS.map((d) => () => agent(
      `${inWorktree('codegate-' + d.key, { notes: false })}

READ-ONLY panel review of the changes on ${BRANCH} vs ${BASE || 'the base branch'} (git diff in ${WORKTREE}) — do NOT edit or fix anything; you only report findings.
DIMENSION — ${d.focus}
Return findings with exact repo-relative file + line + severity (Critical|High|Medium|Low) + title + detail. No findings is a valid answer.`,
      { label: 'codegate:' + d.key, phase: 'CodeGate',
        schema: { type: 'object', additionalProperties: false, required: ["findings"], properties: {"findings":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["file","line","severity","title"],"properties":{"file":{"type":"string"},"line":{"type":"number"},"severity":{"type":"string","enum":["Critical","High","Medium","Low"]},"title":{"type":"string"},"detail":{"type":"string"}}}}} } },
    )))
    const all = rawResults.filter(Boolean).flatMap((r) => r.findings || [])
    const seen = new Set()
    const deduped = []
    for (const f of all) {
      const k = (f.file || '') + ':' + (f.line || 0)
      if (!seen.has(k)) { seen.add(k); deduped.push(f) }
    }
    const scored = deduped.length ? await parallel(deduped.map((f, i) => () => agent(
      `${inWorktree('codegate-score-' + i, { notes: false })}

Verify ONE code-review finding against the actual code (read the files; do NOT edit).
FINDING (JSON): ${JSON.stringify(f)}
Score 0-100 how confident you are the finding is REAL and WORTH FIXING:
- 0: Not confident at all. False positive that does not stand up to light scrutiny, or a pre-existing issue.
- 25: Somewhat confident. Might be real, might be a false positive; could not verify.
- 50: Moderately confident. Verified real, but may be a nitpick or rarely hit in practice.
- 75: Highly confident. Double-checked and verified: very likely real, will be hit in practice, directly impacts functionality (or is explicitly required by CLAUDE.md).
- 100: Absolutely certain. Double-checked, definitely real, will happen frequently; evidence directly confirms it.
Automatic false positives (score 0): pre-existing issues; linter/typechecker/compiler-catchable; pedantic nitpicks; issues on lines the diff did not modify; intentional changes related to the goal.
Return the score and a one-line reason.`,
      { label: 'codegate:score-' + i, phase: 'CodeGate',
        schema: { type: 'object', additionalProperties: false, required: ["score"], properties: {"score":{"type":"number"},"reason":{"type":"string"}} } },
    ).then((v) => ({ ...f, confidence: v ? v.score : 0 })))) : []
    const confirmed = scored.filter(Boolean).filter((f) => f.confidence >= 80)
    if (!confirmed.length) {
      log('CodeGate panel: 0 of ' + all.length + ' raw findings survived verification — passing')
      results.codeGate = { gatePassed: true, critical: 0, high: 0, summary: 'panel: ' + all.length + ' raw, 0 confirmed', panel: { raw: all.length, deduped: deduped.length, confirmed: 0 } }
    } else {
      let passed = false, last = null
      for (let round = 1; round <= 3 && !passed; round++) {
        const dod = results.brief ? `\n\nScope this gate to the task's actual goal — judge findings against what the task set out to achieve; do NOT drift into changes unrelated to it.\nGOAL: ${results.brief.goal || '(none)'}` + ((results.brief.acceptanceCriteria || []).length ? `\nACCEPTANCE CRITERIA:\n- ${results.brief.acceptanceCriteria.join('\n- ')}` : '') : ''
        const carry = round > 1 && last ? `\n\nROUND ${round} of up to 3 — a prior round already ran; BUILD ON what it already found/fixed, do NOT re-review from scratch. Prior round summary: ${last.summary || '(no summary)'}` : ''
        last = await agent(
          `${inWorktree('codegate-lead')}

You are the review-panel LEAD for the changes on ${BRANCH} vs ${BASE || 'the base branch'}. The confirmed findings (confidence >= 80) from the parallel panel are below. Rank them; FIX every Critical and High in the worktree; run the project build/lint (it MUST pass); re-run it after fixes and commit. Fix a Medium or Low finding ONLY when the fix is trivial and zero-risk; otherwise leave it untouched and record it in the knownOpen output array (its exact file, line, severity, title) — a confirmed Medium/Low below the fix bar is NOT wrong, so it must stay known-open for the human, never silently dropped; knownOpen is empty when none remain. You may skip a finding ONLY with an explicit reason it is wrong — record EVERY skipped finding in the skippedFindings output array (its title plus your reason), empty when you skipped none; this is the audit trail a human reviews.
OUTPUT CONTRACT: return gatePassed=true ONLY if every Critical and High finding is fixed or skipped-with-explicit-reason AND the build/lint passes; report critical and high as the counts of findings of each severity left UNRESOLVED after your fixes (both 0 when gatePassed=true).
EVIDENCE: report the exact build/lint command you ran as buildCmd and its numeric exit code as buildExit; if the project has no build/lint, run the closest verification command (e.g. the test suite) and report that instead. The gate rejects gatePassed=true unless buildExit is 0.

FINDINGS (JSON): ${JSON.stringify(confirmed)}` + dod + carry,
          { label: `codegate:lead-r${round}`, phase: 'CodeGate', agentType: 'lirbox:lirbox-code-reviewer',
            schema: { type: 'object', additionalProperties: false, required: ["gatePassed","critical","high","buildCmd","buildExit","skippedFindings","knownOpen"], properties: {"gatePassed":{"type":"boolean"},"critical":{"type":"number"},"high":{"type":"number"},"summary":{"type":"string"},"buildCmd":{"type":"string"},"buildExit":{"type":"number"},"skippedFindings":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["title","reason"],"properties":{"title":{"type":"string"},"reason":{"type":"string"}}}},"knownOpen":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["file","line","severity","title"],"properties":{"file":{"type":"string"},"line":{"type":"number"},"severity":{"type":"string"},"title":{"type":"string"}}}}} } },
        )
        passed = last && last.gatePassed && last.buildExit === 0
      }
      if (!passed) throw new Error('CodeGate failed: unresolved Critical/High after 3 rounds — ' + (last && last.summary || ''))
      results.codeGate = { ...last, panel: { raw: all.length, deduped: deduped.length, confirmed: confirmed.length } }
    }
  }
  done.add('CodeGate')
  await checkpoint('CodeGate')
}

return { workflow: NAME, status: 'complete', branch: BRANCH, worktree: WORKTREE, ticket: TICKET, phasesDone: [...done], results }
